export const productos = [
  {
    id: "te-blanco-400ml",
    nombre: "Hatsu - TÉ BLANCO 400 ml",
    descripcion: "Té Blanco 400 ml",
    imagen: "/productos/te-blanco-400ml.png",
    precio: "$5.000",
  },
  {
    id: "te-amarillo-400ml",
    nombre: "Hatsu - TÉ AMARILLO 400 ml",
    descripcion: "Té Amarillo 400 ml",
    imagen: "/productos/te-amarillo-400ml.png",
    precio: "$5.000",
  },
  {
    id: "te-verde-400ml",
    nombre: "Hatsu - TÉ VERDE 400 ml",
    descripcion: "Té Verde 400 ml",
    imagen: "/productos/te-verde-400ml.png",
    precio: "$5.000",
  },
  {
    id: "te-azul-400ml",
    nombre: "Hatsu - TÉ AZUL 400 ml",
    descripcion: "Té Azul 400 ml",
    imagen: "/productos/te-azul-400ml.png",
    precio: "$5.000",
  },
  {
    id: "te-lila-400ml",
    nombre: "Hatsu - TÉ LILA 400 ml",
    descripcion: "Té Lila 400 ml",
    imagen: "/productos/te-lila-400ml.png",
    precio: "$5.000",
  },
  {
    id: "te-rosado-claro-400ml",
    nombre: "Hatsu - TÉ ROSADO CLARO 400 ml",
    descripcion: "Té Rosado Claro 400 ml",
    imagen: "/productos/te-rosado-claro-400ml.png",
    precio: "$5.000",
  },
  {
    id: "te-rosa-400ml",
    nombre: "Hatsu - TÉ ROSA 400 ml",
    descripcion: "Té Rosa 400 ml",
    imagen: "/productos/te-rosa-400ml.png",
    precio: "$5.000",
  },
  {
    id: "te-rojo-400ml",
    nombre: "Hatsu - TÉ ROJO 400 ml",
    descripcion: "Té Rojo 400 ml",
    imagen: "/productos/te-rojo-400ml.png",
    precio: "$5.000",
  },
  {
    id: "te-negro-400ml",
    nombre: "Hatsu - TÉ NEGRO 400 ml",
    descripcion: "Té Negro 400 ml",
    imagen: "/productos/te-negro-400ml.png",
    precio: "$5.000",
  },
  {
    id: "te-blanco-250ml",
    nombre: "Hatsu - TÉ BLANCO 250 ml",
    descripcion: "Té Blanco 250 ml",
    imagen: "/productos/te-blanco-250ml.png",
    precio: "$4.000",
  },
  {
    id: "te-amarillo-250ml",
    nombre: "Hatsu - TÉ AMARILLO 250 ml",
    descripcion: "Té Amarillo 250 ml",
    imagen: "/productos/te-amarillo-250ml.png",
    precio: "$4.000",
  },
  {
    id: "te-lila-250ml",
    nombre: "Hatsu - TÉ LILA 250 ml",
    descripcion: "Té Lila 250 ml",
    imagen: "/productos/te-lila-250ml.png",
    precio: "$4.000",
  },
  {
    id: "te-rosa-250ml",
    nombre: "Hatsu - TÉ ROSA 250 ml",
    descripcion: "Té Rosa 250 ml",
    imagen: "/productos/te-rosa-250ml.png",
    precio: "$4.000",
  },
  {
    id: "te-negro-250ml",
    nombre: "Hatsu - TÉ NEGRO 250 ml",
    descripcion: "Té Negro 250 ml",
    imagen: "/productos/te-negro-250ml.png",
    precio: "$4.000",
  },
  {
    id: "te-blanco-200ml",
    nombre: "Hatsu - TÉ BLANCO 200 ml",
    descripcion: "Té Blanco 200 ml – 1L",
    imagen: "/productos/te-blanco-200ml.png",
    precio: "$3.000",
  },
  {
    id: "te-amarillo-200ml",
    nombre: "Hatsu - TÉ AMARILLO 200 ml",
    descripcion: "Té Amarillo 200 ml – 1L",
    imagen: "/productos/te-amarillo-200ml.png",
    precio: "$3.000",
  },
  {
    id: "te-azul-200ml",
    nombre: "Hatsu - TÉ AZUL 200 ml",
    descripcion: "Té Azul 200 ml – 1L",
    imagen: "/productos/te-azul-200ml.png",
    precio: "$3.000",
  },
  {
    id: "te-lila-200ml",
    nombre: "Hatsu - TÉ LILA 200 ml",
    descripcion: "Té Lila 200 ml – 1L",
    imagen: "/productos/te-lila-200ml.png",
    precio: "$3.000",
  },
];
